---
- name: Setup neovim facts
  ansible.builtin.set_fact:
    nvim_cfg_dir: "{{ ansible_facts['user_dir'] }}/.config/nvim"
- name: "Remove .config/nvim if it exists"
  ansible.builtin.file:
    path: "{{ nvim_cfg_dir }}"
    state: absent

- name: "Create path"
  ansible.builtin.file:
    path: "{{ nvim_cfg_dir }}"
    state: directory
    mode: '744'
- name: Copy base .config/nvim
  ansible.builtin.copy:
    src: "{{ repo_root_controller }}/.config/nvim/"
    dest: "{{ nvim_cfg_dir }}/"
    mode: '744'
- name: Apply templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ nvim_cfg_dir }}/{{ item.dest }}"
    mode: '744'
  loop:
    - src: templates/lsp.lua.j2
      dest: lua/plugins/lsp.lua
    - src: templates/theme.lua.j2
      dest: lua/plugins/theme.lua
    - src: templates/lualine.lua.j2
      dest: lua/plugins/lualine.lua
